In [1]:
#Routine stuff
import numpy as np
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
#Importing the training dataset into dataframe
df = pd.read_csv("train.csv",delimiter=",")
df = df.drop('Unnamed: 0',axis=1)
df.CLASSIFICATION = pd.Categorical(df.CLASSIFICATION)
df['CODE'] = df.CLASSIFICATION.cat.codes #Converting classes (names) to codes
df = df.drop('CLASSIFICATION',axis=1)
df.head()

apr  gmt  1993  writes  references  article  sender  people  university  1  \
0    2    2     2       1           1        1       1       2           1  0   
1    1    1     1       1           1        0       1       1           0  0   
2    1    1     1       2           1        0       0       0           0  0   
3    1    1     1       2           1        2       0       0           0  0   
4    0    1     1       1           1        0       1       2           0  0   

           ...            finland  bikes  livesey@solntze.wpd.sgi.com  shit  \
0          ...                  0      0                            0     0   
1          ...                  0      0                            0     0   
2          ...                  0      0                            0     0   
3          ...                  0      0                            0     0   
4          ...                  0      0                            0     0   

   spot  justify  explained  52  learning         CLASSIFICATION  
0     0        0          0   0         0  talk.politics.mideast  
1     0        0          0   0         0  talk.politics.mideast  
2     0        0          0   0         0  talk.politics.mideast  
3     0        0          0   0         0  talk.politics.mideast  
4     0        0          0   0         0  talk.politics.mideast  

[5 rows x 2001 columns]

In [5]:
data = df.values #training dataframe to numpy array
data

array([[ 2,  2,  2, ...,  0,  0, 17],
       [ 1,  1,  1, ...,  0,  0, 17],
       [ 1,  1,  1, ...,  0,  0, 17],
       ..., 
       [ 1,  1,  0, ...,  0,  1, 19],
       [ 1,  1,  1, ...,  0,  0, 19],
       [ 1,  1,  1, ...,  0,  0, 19]])

In [6]:
y_train = data[:,-1]#separating ouput
y_train

array([17, 17, 17, ..., 19, 19, 19])

In [7]:
x_train = data[:,:-1] #separating input
x_train

array([[2, 2, 2, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ..., 
       [1, 1, 0, ..., 0, 0, 1],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])

In [8]:
#importing test dataset just like done for train dataset
df_test = pd.read_csv("test.csv",delimiter=",")
df_test = df_test.drop('Unnamed: 0',axis=1)
df_test.CLASSIFICATION = pd.Categorical(df_test.CLASSIFICATION)
df_test['CODE'] = df_test.CLASSIFICATION.cat.codes
df_test = df_test.drop('CLASSIFICATION',axis=1)
data_test = df_test.values
y_test = data_test[:,-1]
x_test = data_test[:,:-1]

In [10]:
y_train_pred = clf.predict(x_train)
print(classification_report(y_train,y_train_pred))
print(confusion_matrix(y_train,y_train_pred))
#PREDICTIONS ON TRAINING DATA

             precision    recall  f1-score   support

          0       0.76      0.88      0.82       800
          1       0.88      0.81      0.84       800
          2       0.91      0.86      0.88       800
          3       0.87      0.92      0.89       800
          4       0.89      0.95      0.92       800
          5       0.92      0.93      0.92       800
          6       0.87      0.91      0.89       800
          7       0.91      0.96      0.93       800
          8       0.92      0.97      0.95       800
          9       0.97      0.97      0.97       800
         10       0.97      0.95      0.96       800
         11       0.96      0.92      0.94       800
         12       0.87      0.89      0.88       800
         13       0.95      0.92      0.93       800
         14       0.94      0.95      0.94       800
         15       0.96      0.99      0.98       797
         16       0.75      0.93      0.83       800
         17       0.95      0.88      0.91   

In [9]:
clf = MultinomialNB()
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
#PREDICTIONS ON TESTING DATA

             precision    recall  f1-score   support

          0       0.73      0.88      0.79       200
          1       0.86      0.80      0.83       200
          2       0.84      0.81      0.83       200
          3       0.83      0.85      0.84       200
          4       0.86      0.93      0.89       200
          5       0.90      0.89      0.89       200
          6       0.85      0.85      0.85       200
          7       0.85      0.93      0.89       200
          8       0.92      0.97      0.94       200
          9       0.95      0.96      0.96       200
         10       0.96      0.95      0.96       200
         11       0.98      0.88      0.93       200
         12       0.80      0.85      0.83       200
         13       0.92      0.88      0.90       200
         14       0.89      0.92      0.90       200
         15       0.94      0.99      0.97       200
         16       0.68      0.87      0.76       200
         17       0.96      0.86      0.91   